### ISSUE TITLE
Cyber-bulling in lab_02 readme

### ISSUE THREAD

**Issue by Justarone** [SpectralOne/bmstu-oop#3]
Привет. Вот у тебя написано "уважаемые студенты" в ридми, а что если я не студент, а 30летний манагер по продажам и просто хочу научиться писать неиндусский код, отфильтрованный мастером неиндусом? получается, я для тебя неуважаемый, так? просто говно под ботинком, да?

**Comment by mRrvz** [comment]
Полностью согласен. Думаю, стоит извиниться...

**Comment by SpectralOne** [comment]
Если тебе мои ридми не нравятся, то ты со мной раз на раз выйди, а не дискуссии на гитхабе открывай..

**Comment by Justarone** [comment]
Ааааоооо ого... Это ты такой смелый, потому что накококочался или потому что "да я в другом городе и хуй ты прилетишь из-за коронавируса"?

**Comment by SpectralOne** [comment]
Сильный не тот, кто в качалке качался, а кто упал и поднялся..

**Comment by Justarone** [comment]
Блин, ну тут мне даже ответить нечего, вопросов больше не осталось...
